### ISSUE TITLE
problems with FeedbackWindow and subclasses

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/area-builder#115]
Noted while converting to ES6 class in https://github.com/phetsims/tasks/issues/1049.

- [x] Subclasses YouBuiltWindow and YouEnteredWindow pass options by both `super(...,options)` and `this.mutate( options )`. This is an anti-pattern that can get you into trouble with transform-related options.  Pass options once, using one of these methods.

- [x] FeedbackWindow goes to the trouble of calling `options = merge( {...}, options )`, then does not pass `options` to super.

Low priority, but worth fixing at some point.

**Comment by jbphet** [comment]
For the first item above, I removed the calls to `.mutate` and the behavior was unchanged.  For the second, I changed the call to the superconstructor to pass in the options instead of the decomposed options that it was using, and that appears to have worked too.

I tested using number, short, and long strings, and the position of the `YouBuiltWindow` and the `YouEnteredWindow` was unchanged.

Seems like that should do it.  Closing.
