### ISSUE TITLE
Dark green squares "observed" on 'Find the Area' challenges

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/area-builder#61]
Can't reproduce and don't have screenshot...

I've once observed that when you drag the green blocks on top of the purple shape, that dark green blocks would appear (rather than the transparent green).

**Comment by jbphet** [comment]
I fixed some issues related to colors of squares, race conditions, and such in #73.  The problem described in this issue hasn't been seen since, so I think they were probably related, and the commits associated with the other issue fixed this one.  Closing, will reopen if this issue is seen again when this sim is redeployed in support of translation.
